"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const API_V2_DATA_EXPORT_FORBIDDEN_REASONS = [
    'DISABLED_EXPORT_DATASET',
    'DISABLED_EXPORT_CONNECTION',
    'DISABLED_EXPORT_TENANT',
    'PROHIBITED_EXPORT_TENANT',
    'PROHIBITED_EXPORT_CONNECTION',
    'PROHIBITED_EXPORT_PIVOT_TABLE',
    'PROHIBITED_EXPORT_QL_CHART',
    'PROHIBITED_EXPORT_TYPED_QUERY',
];
