"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.addAxisFormatter = exports.addAxisFormatting = exports.isAxisLabelDateFormat = exports.getAxisFormatting = exports.getAxisType = void 0;
var getAxisType_1 = require("./getAxisType");
Object.defineProperty(exports, "getAxisType", { enumerable: true, get: function () { return getAxisType_1.getAxisType; } });
var get_axis_formatting_1 = require("./get-axis-formatting");
Object.defineProperty(exports, "getAxisFormatting", { enumerable: true, get: function () { return get_axis_formatting_1.getAxisFormatting; } });
var isAxisLabelDateFormat_1 = require("./isAxisLabelDateFormat");
Object.defineProperty(exports, "isAxisLabelDateFormat", { enumerable: true, get: function () { return isAxisLabelDateFormat_1.isAxisLabelDateFormat; } });
var addAxisFormatting_1 = require("./addAxisFormatting");
Object.defineProperty(exports, "addAxisFormatting", { enumerable: true, get: function () { return addAxisFormatting_1.addAxisFormatting; } });
var addAxisFormatter_1 = require("./addAxisFormatter");
Object.defineProperty(exports, "addAxisFormatter", { enumerable: true, get: function () { return addAxisFormatter_1.addAxisFormatter; } });
