"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlaceholderId = void 0;
var PlaceholderId;
(function (PlaceholderId) {
    PlaceholderId["X"] = "x";
    PlaceholderId["Y"] = "y";
    PlaceholderId["Y2"] = "y2";
    PlaceholderId["FlatTableColumns"] = "flat-table-columns";
    PlaceholderId["Geopoint"] = "geopoint";
    PlaceholderId["Geopoligon"] = "geopolygon";
    PlaceholderId["Measures"] = "measures";
    PlaceholderId["Size"] = "size";
    PlaceholderId["Points"] = "points";
    PlaceholderId["Dimensions"] = "dimensions";
    PlaceholderId["PivotTableColumns"] = "pivot-table-columns";
    PlaceholderId["PivotTableRows"] = "rows";
    PlaceholderId["Polyline"] = "polyline";
    PlaceholderId["Grouping"] = "grouping";
    PlaceholderId["Heatmap"] = "heatmap";
    PlaceholderId["Colors"] = "colors";
    PlaceholderId["DashboardFilters"] = "dashboard-filters";
    PlaceholderId["DashboardParameters"] = "dashboard-parameters";
    PlaceholderId["Filters"] = "filters";
    PlaceholderId["Labels"] = "labels";
    PlaceholderId["LayerFilters"] = "layer-filters";
    PlaceholderId["Segments"] = "segments";
    PlaceholderId["Shapes"] = "shapes";
    PlaceholderId["Sort"] = "sort";
    PlaceholderId["Tooltips"] = "tooltips";
    PlaceholderId["Available"] = "available";
})(PlaceholderId || (exports.PlaceholderId = PlaceholderId = {}));
