export enum MenuItemsIds {
    EXPORT = 'export',
    EXPORT_CSV = 'exportCsv',
    EXPORT_ODS = 'exportOds',
    EXPORT_XLSX = 'exportXlsx',
    EXPORT_MARKDOWN = 'exportMarkdown',
    EXPORT_PDF = 'exportPdf',
    EXPORT_WIKI = 'exportWiki',
    EXPORT_SCREENSHOT = 'exportScreenshot',
    INSPECTOR = 'inspector',
    COMMENTS = 'comments',
    SHOW_COMMENTS = 'showComments',
    HIDE_COMMENTS = 'hideComments',
    SCREENSHOT = 'screenshot',
    NEW_WINDOW = 'openInNewWindow',
    OPEN_AS_TABLE = 'openAsTable',
    GET_LINK = 'getLink',
    SOURCE = 'source',
    EDIT = 'edit',
    COPY = 'copy',
    MOVE = 'move',
    RENAME = 'rename',
    DUPLICATE = 'duplicate',
    DELETE = 'delete',
    EMBEDDED = 'embedded',
    SETTINGS = 'settings',
    ALERTS = 'alerts',
    FULLSCREEEN = 'fullscreen',
    /** Плоское дерево строк таблицы (рейс → сегменты): развернуть все группы */
    FLAT_TABLE_ROW_TREE_EXPAND_ALL = 'flatTableRowTreeExpandAll',
    /** Плоское дерево строк таблицы: свернуть все группы */
    FLAT_TABLE_ROW_TREE_COLLAPSE_ALL = 'flatTableRowTreeCollapseAll',
}
