#!/usr/bin/env bash
# Build YDL: official UI image + server patch overlay (no fat tree).
set -euo pipefail

source "$(dirname "$0")/lib/env.sh"

GIT_SHA="$(git -C "${YDL_REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || echo local)"
PREFIX="${YDL_IMAGE_PREFIX:-ydl}"
VC="${VENDOR_DATALENS}/versions-config.json"
UI_VER="$(jq -r '.uiVersion // "0.0.0"' "$VC" 2>/dev/null || echo 0.0.0)"
AUTH_VER="$(jq -r '.authVersion // "0.0.0"' "$VC" 2>/dev/null || echo 0.0.0)"
US_VER="$(jq -r '.usVersion // "1.39.0"' "$VC" 2>/dev/null || echo 1.39.0)"
LEGACY_AUTH="${YDL_LEGACY_AUTH:-0}"
BUILD_CUSTOM_US="${YDL_BUILD_CUSTOM_US:-0}"
UI_TAG="${UI_TAG:-${PREFIX}/datalens-ui:${UI_VER}-official-${GIT_SHA}}"
AUTH_TAG="${AUTH_TAG:-${PREFIX}/datalens-auth:${AUTH_VER}-ydl-${GIT_SHA}}"
US_TAG="${US_TAG:-${PREFIX}/datalens-us:${US_VER}-ydl-${GIT_SHA}}"
BUILD_UI="${BUILD_UI:-1}"
IMAGES_ENV="${OVERLAY_PLATFORM}/.ydl-built-images.env"

bash "$(dirname "$0")/sync-official-image-pins.sh" >/dev/null
source "${OVERLAY_PLATFORM}/.official-images.env"

echo "=== YDL OS build (official + server patches) ==="
echo "repo=${YDL_REPO_ROOT} sha=${GIT_SHA}"
bash "$(dirname "$0")/verify-vendor-pristine.sh"

built=0

if [[ "$LEGACY_AUTH" == "1" ]]; then
  echo "WARN: YDL_LEGACY_AUTH=1 not supported without legacy snapshot"
fi
AUTH_TAG="${OFFICIAL_AUTH_IMAGE}"
US_TAG="${OFFICIAL_US_IMAGE}"

if [[ "${BUILD_UI}" == "1" ]]; then
  echo "publish UI (official client + server patches)..."
  export YDL_UI_CLIENT_BUILD="${YDL_UI_CLIENT_BUILD:-1}"
  export YDL_UI_CLIENT_TIER="${YDL_UI_CLIENT_TIER:-corp}"
  bash "$(dirname "$0")/publish-ui-overlay-dist.sh"
  UI_TAG="$(grep '^YDL_UI_IMAGE=' "${IMAGES_ENV}" | cut -d= -f2-)"
  built=1
fi

if [[ "${BUILD_CORP_BACKEND:-1}" == "1" ]]; then
  echo "patch control-api + data-api (PARAMETERS-YDL-OS)..."
  bash "$(dirname "$0")/build-corp-backend-patch.sh"
  built=1
fi

YDL_CONTROL_API_IMAGE="${YDL_CONTROL_API_IMAGE:-}"
YDL_DATA_API_IMAGE="${YDL_DATA_API_IMAGE:-}"
if [[ -f "${OVERLAY_PLATFORM}/.ydl-corp-backend.env" ]]; then
  # shellcheck disable=SC1090
  source "${OVERLAY_PLATFORM}/.ydl-corp-backend.env"
fi

cat >"${IMAGES_ENV}" <<EOF
# Generated by integration/build.sh
YDL_UI_IMAGE=${UI_TAG}
YDL_AUTH_IMAGE=${AUTH_TAG}
YDL_US_IMAGE=${US_TAG}
YDL_CONTROL_API_IMAGE=${YDL_CONTROL_API_IMAGE:-}
YDL_DATA_API_IMAGE=${YDL_DATA_API_IMAGE:-}
YDL_BUILD_SHA=${GIT_SHA}
YDL_OFFICIAL_STACK=1
YDL_BUILD_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
OFFICIAL_US_IMAGE=${OFFICIAL_US_IMAGE}
OFFICIAL_AUTH_IMAGE=${OFFICIAL_AUTH_IMAGE}
EOF
if [[ -f "${OVERLAY_PLATFORM}/.ydl-corp-backend.env" ]]; then
  grep -E '^OFFICIAL_(CONTROL|DATA)_API_IMAGE=' "${OVERLAY_PLATFORM}/.ydl-corp-backend.env" >>"${IMAGES_ENV}" || true
fi
echo "Wrote ${IMAGES_ENV}"
echo "=== build done (built=${built}) ==="
