#!/usr/bin/env bash
# Build hardened YDL images: official ghcr bases + apt upgrade + overlay patches.
set -euo pipefail

source "$(dirname "$0")/lib/env.sh"

export DOCKER_BUILDKIT=1
GIT_SHA="$(git -C "${YDL_REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || echo local)"
PREFIX="${YDL_IMAGE_PREFIX:-akrasnov87}"
VC="${VENDOR_DATALENS}/versions-config.json"
UI_VER="$(jq -r '.uiVersion // "0.0.0"' "$VC")"
AUTH_VER="$(jq -r '.authVersion // "0.0.0"' "$VC")"
US_VER="$(jq -r '.version // "0.413.0"' "${OVERLAY_COMPONENTS}/datalens-us/package.json")"
BACKEND_VER="$(jq -r '.backendVersion // "0.0.0"' "$VC")"
META_VER="$(jq -r '.metaManagerVersion // "0.0.0"' "$VC")"

export UI_TAG="${UI_TAG:-${PREFIX}/datalens-ui:${UI_VER}-ydl-${GIT_SHA}}"
export AUTH_TAG="${AUTH_TAG:-${PREFIX}/datalens-auth:${AUTH_VER}-ydl-${GIT_SHA}}"
export US_TAG="${US_TAG:-${PREFIX}/datalens-us:${US_VER}-ydl-${GIT_SHA}}"

echo "=== hardened build (SHA=${GIT_SHA}) ==="
bash "$(dirname "$0")/verify-vendor-pristine.sh"
bash "$(dirname "$0")/sync-official-image-pins.sh"

docker pull "ghcr.io/datalens-tech/datalens-auth:${AUTH_VER}"
docker pull ghcr.io/datalens-tech/datalens-postgres:16
docker pull ghcr.io/datalens-tech/datalens-temporal:1.27.2
docker pull "ghcr.io/datalens-tech/datalens-control-api:${BACKEND_VER}"
docker pull "ghcr.io/datalens-tech/datalens-data-api:${BACKEND_VER}"
docker pull "ghcr.io/datalens-tech/datalens-meta-manager:${META_VER}"
docker pull "ghcr.io/datalens-tech/datalens-ui:${UI_VER}"
docker pull quay.io/nginx/nginx-unprivileged:stable-alpine

if [[ -d "${OVERLAY_COMPONENTS}/datalens-ui" ]]; then
  echo "UI build -> ${UI_TAG}"
  if [[ ! -d "${OVERLAY_COMPONENTS}/datalens-ui/node_modules" ]]; then
    (cd "${OVERLAY_COMPONENTS}/datalens-ui" && HUSKY=0 npm ci --no-audit --no-fund)
  fi
  set +e
  docker build --pull \
    --build-arg app_version="${GIT_SHA}" \
    -t "${UI_TAG}" "${OVERLAY_COMPONENTS}/datalens-ui"
  UI_BUILD_RC=$?
  set -e
  if [[ "$UI_BUILD_RC" -ne 0 ]]; then
    echo "WARN: full UI build failed; hardened base + apt upgrade"
    docker build --pull \
      --build-arg BASE_IMAGE="ghcr.io/datalens-tech/datalens-ui:${UI_VER}" \
      --build-arg app_version="${GIT_SHA}" \
      -f "${OVERLAY_COMPONENTS}/datalens-ui/Dockerfile.ydl-hardened" \
      -t "${UI_TAG}" "${OVERLAY_COMPONENTS}/datalens-ui"
  fi
fi

if [[ -d "${OVERLAY_COMPONENTS}/datalens-auth" ]]; then
  echo "auth -> ${AUTH_TAG}"
  docker build --pull \
    --build-arg DATALENS_AUTH_BASE_IMAGE="ghcr.io/datalens-tech/datalens-auth:${AUTH_VER}" \
    -f "${OVERLAY_COMPONENTS}/datalens-auth/Dockerfile" \
    -t "${AUTH_TAG}" "${OVERLAY_COMPONENTS}/datalens-auth"
fi

if [[ -d "${OVERLAY_COMPONENTS}/datalens-us" && -f "${OVERLAY_COMPONENTS}/datalens-us/Dockerfile" ]]; then
  echo "US -> ${US_TAG}"
  mkdir -p "${OVERLAY_COMPONENTS}/datalens-us/dist"
  docker build --pull \
    --build-arg app_version="${GIT_SHA}" \
    -t "${US_TAG}" "${OVERLAY_COMPONENTS}/datalens-us"
fi

# Align with build.sh env names for release-full
cat >"${OVERLAY_PLATFORM}/.ydl-built-images.env" <<EOF
# Generated by integration/build-hardened.sh @ $(date -u +%Y-%m-%dT%H:%M:%SZ)
YDL_UI_IMAGE=${UI_TAG}
YDL_AUTH_IMAGE=${AUTH_TAG}
YDL_US_IMAGE=${US_TAG}
YDL_BUILD_SHA=${GIT_SHA}
YDL_BUILD_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF
echo "Wrote ${OVERLAY_PLATFORM}/.ydl-built-images.env"
echo "=== hardened build OK ==="
