#!/usr/bin/env bash
# Patch ghcr control-api + data-api with YDL OS backend lib (PARAMETERS-YDL-OS, MSSQL).
set -euo pipefail

source "$(dirname "$0")/lib/env.sh"

export DOCKER_BUILDKIT=1
VC="${VENDOR_DATALENS}/versions-config.json"
BACKEND_VER="$(jq -r '.backendVersion' "$VC")"
GIT_SHA="$(git -C "${YDL_REPO_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || echo local)"
PREFIX="${YDL_IMAGE_PREFIX:-ydl}"
BUILD_UTC="$(date -u +%Y%m%dT%H%M%S)"
CTX="${OVERLAY_COMPONENTS}/datalens-backend"
DF="${YDL_REPO_ROOT}/integration/docker/Dockerfile.ydl-backend-api.patch"

CONTROL_TAG="${YDL_CONTROL_API_IMAGE:-${PREFIX}/datalens-control-api:${BACKEND_VER}-corp-${GIT_SHA}-${BUILD_UTC}}"
DATA_TAG="${YDL_DATA_API_IMAGE:-${PREFIX}/datalens-data-api:${BACKEND_VER}-corp-${GIT_SHA}-${BUILD_UTC}}"
BASE_CONTROL="ghcr.io/datalens-tech/datalens-control-api:${BACKEND_VER}"
BASE_DATA="ghcr.io/datalens-tech/datalens-data-api:${BACKEND_VER}"

for f in \
  lib/dl_api_lib/dl_api_lib/dataset/validator.py \
  lib/dl_core/dl_core/data_source/base.py \
  lib/dl_core/dl_core/components/accessor.py \
  lib/dl_query_processing/dl_query_processing/compilation/formula_compiler.py; do
  [[ -f "${CTX}/${f}" ]] || {
    echo "FATAL: missing ${CTX}/${f}" >&2
    exit 1
  }
done

echo "=== corp backend patch (PARAMETERS-YDL-OS + MSSQL) ==="
echo "sha=${GIT_SHA} backend=${BACKEND_VER}"

docker pull "${BASE_CONTROL}"
docker pull "${BASE_DATA}"

docker build \
  --build-arg BASE_IMAGE="${BASE_CONTROL}" \
  -f "${DF}" \
  -t "${CONTROL_TAG}" \
  "${CTX}"

docker build \
  --build-arg BASE_IMAGE="${BASE_DATA}" \
  -f "${DF}" \
  -t "${DATA_TAG}" \
  "${CTX}"

# Sanity: patched validator must not contain upstream constraint error text
docker run --rm --entrypoint grep "${CONTROL_TAG}" \
  -c "Value constraint is required for string parameters" \
  /venv/lib/python3.10/site-packages/dl_api_lib/dataset/validator.py && {
  echo "FATAL: validator patch not applied" >&2
  exit 1
} || true

docker run --rm --entrypoint sh "${CONTROL_TAG}" -c \
  'grep -q "YDL OS" /venv/lib/python3.10/site-packages/dl_api_lib/dataset/validator.py'

docker run --rm --entrypoint grep "${DATA_TAG}" \
  -q "_repka_mssql_ds_param" \
  /venv/lib/python3.10/site-packages/dl_core/data_source/base.py

ENV_FILE="${OVERLAY_PLATFORM}/.ydl-corp-backend.env"
cat >"${ENV_FILE}" <<EOF
# Generated by integration/build-corp-backend-patch.sh @ $(date -u +%Y-%m-%dT%H:%M:%SZ)
YDL_CONTROL_API_IMAGE=${CONTROL_TAG}
YDL_DATA_API_IMAGE=${DATA_TAG}
OFFICIAL_CONTROL_API_IMAGE=${BASE_CONTROL}
OFFICIAL_DATA_API_IMAGE=${BASE_DATA}
EOF

# Merge into built-images env for compose
BI="${OVERLAY_PLATFORM}/.ydl-built-images.env"
if [[ -f "${BI}" ]]; then
  grep -v '^YDL_CONTROL_API_IMAGE=' "${BI}" | grep -v '^YDL_DATA_API_IMAGE=' >"${BI}.tmp" || true
  mv "${BI}.tmp" "${BI}"
fi
cat "${ENV_FILE}" >>"${BI}"

echo "Wrote ${ENV_FILE}"
echo "control-api: ${CONTROL_TAG}"
echo "data-api:    ${DATA_TAG}"
echo "=== corp backend patch OK ==="
