#!/usr/bin/env bash
# Rebuild vendor postgres + temporal with security upgrades (reduce critical CVE count).
set -euo pipefail

source "$(dirname "$0")/lib/env.sh"
export DOCKER_BUILDKIT=1

GIT_SHA="$(git -C "$YDL_REPO_ROOT" rev-parse --short=12 HEAD)"
PREFIX="${YDL_IMAGE_PREFIX:-ydl}"
POSTGRES_TAG="${PREFIX}/datalens-postgres:16-hardened-${GIT_SHA}"
TEMPORAL_TAG="${PREFIX}/datalens-temporal:1.28.1-hardened-${GIT_SHA}"
TEMPORAL_VER="${TEMPORAL_VERSION:-1.28.1}"

echo "=== hardened vendor images (SHA=${GIT_SHA}) ==="

echo "build postgres -> ${POSTGRES_TAG}"
docker build --pull \
  -f "${VENDOR_DATALENS}/postgres/dockerfile" \
  --build-arg POSTGRES_VERSION=16 \
  -t "${POSTGRES_TAG}" \
  "${VENDOR_DATALENS}/postgres"

echo "build temporal -> ${TEMPORAL_TAG}"
docker build --pull \
  -f "${VENDOR_DATALENS}/temporal/dockerfile" \
  --build-arg TEMPORAL_VERSION="${TEMPORAL_VER}" \
  -t "${TEMPORAL_TAG}" \
  "${VENDOR_DATALENS}/temporal"

upgrade_os_packages() {
  local img="$1"
  local os="$2"
  local user="$3"
  local hard="${img}-upgraded"
  echo "upgrade layer ${hard} (${os})"
  if [[ "$os" == "alpine" ]]; then
    docker build -t "${hard}" - <<EOF
FROM ${img}
USER root
RUN apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*
USER ${user}
EOF
  else
    docker build -t "${hard}" - <<EOF
FROM ${img}
USER root
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && apt-get clean && rm -rf /var/lib/apt/lists/*
USER ${user}
EOF
  fi
  docker tag "${hard}" "${img}"
}

upgrade_os_packages "${POSTGRES_TAG}" debian postgres
upgrade_os_packages "${TEMPORAL_TAG}" alpine temporal

VENDOR_ENV="${OVERLAY_PLATFORM}/.ydl-hardened-vendor.env"
cat >"${VENDOR_ENV}" <<EOF
# Generated by integration/build-hardened-vendor-images.sh
YDL_POSTGRES_IMAGE=${POSTGRES_TAG}
YDL_TEMPORAL_IMAGE=${TEMPORAL_TAG}
EOF
echo "Wrote ${VENDOR_ENV}"
echo "=== done ==="
