#!/usr/bin/env bash
# Write ghcr.io/datalens-tech image pins from vendor/datalens/versions-config.json
set -euo pipefail

source "$(dirname "$0")/lib/env.sh"

VC="${VENDOR_DATALENS}/versions-config.json"
OUT="${OVERLAY_PLATFORM}/.official-images.env"

if [[ ! -f "$VC" ]]; then
  echo "FATAL: missing $VC" >&2
  exit 1
fi

backend="$(jq -r '.backendVersion' "$VC")"
ui="$(jq -r '.uiVersion' "$VC")"
us="$(jq -r '.usVersion' "$VC")"
auth="$(jq -r '.authVersion' "$VC")"
meta="$(jq -r '.metaManagerVersion' "$VC")"
release="$(jq -r '.releaseVersion' "$VC")"

cat >"$OUT" <<EOF
# Generated by integration/sync-official-image-pins.sh — official datalens-tech/datalens pins
# releaseVersion=${release}
OFFICIAL_POSTGRES_IMAGE=ghcr.io/datalens-tech/datalens-postgres:16
OFFICIAL_TEMPORAL_IMAGE=ghcr.io/datalens-tech/datalens-temporal:1.27.2
OFFICIAL_CONTROL_API_IMAGE=ghcr.io/datalens-tech/datalens-control-api:${backend}
OFFICIAL_DATA_API_IMAGE=ghcr.io/datalens-tech/datalens-data-api:${backend}
OFFICIAL_META_MANAGER_IMAGE=ghcr.io/datalens-tech/datalens-meta-manager:${meta}
OFFICIAL_UI_REFERENCE_IMAGE=ghcr.io/datalens-tech/datalens-ui:${ui}
OFFICIAL_US_IMAGE=ghcr.io/datalens-tech/datalens-us:${us}
OFFICIAL_US_REFERENCE_IMAGE=ghcr.io/datalens-tech/datalens-us:${us}
OFFICIAL_AUTH_IMAGE=ghcr.io/datalens-tech/datalens-auth:${auth}
OFFICIAL_AUTH_REFERENCE_IMAGE=ghcr.io/datalens-tech/datalens-auth:${auth}
VENDOR_RELEASE_VERSION=${release}
EOF

echo "Wrote $OUT (release ${release})"
