"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MenuItemsIds = void 0;
var MenuItemsIds;
(function (MenuItemsIds) {
    MenuItemsIds["EXPORT"] = "export";
    MenuItemsIds["EXPORT_CSV"] = "exportCsv";
    MenuItemsIds["EXPORT_ODS"] = "exportOds";
    MenuItemsIds["EXPORT_XLSX"] = "exportXlsx";
    MenuItemsIds["EXPORT_MARKDOWN"] = "exportMarkdown";
    MenuItemsIds["EXPORT_PDF"] = "exportPdf";
    MenuItemsIds["EXPORT_WIKI"] = "exportWiki";
    MenuItemsIds["EXPORT_SCREENSHOT"] = "exportScreenshot";
    MenuItemsIds["INSPECTOR"] = "inspector";
    MenuItemsIds["COMMENTS"] = "comments";
    MenuItemsIds["SHOW_COMMENTS"] = "showComments";
    MenuItemsIds["HIDE_COMMENTS"] = "hideComments";
    MenuItemsIds["SCREENSHOT"] = "screenshot";
    MenuItemsIds["NEW_WINDOW"] = "openInNewWindow";
    MenuItemsIds["OPEN_AS_TABLE"] = "openAsTable";
    MenuItemsIds["GET_LINK"] = "getLink";
    MenuItemsIds["SOURCE"] = "source";
    MenuItemsIds["EDIT"] = "edit";
    MenuItemsIds["COPY"] = "copy";
    MenuItemsIds["MOVE"] = "move";
    MenuItemsIds["RENAME"] = "rename";
    MenuItemsIds["DUPLICATE"] = "duplicate";
    MenuItemsIds["DELETE"] = "delete";
    MenuItemsIds["EMBEDDED"] = "embedded";
    MenuItemsIds["SETTINGS"] = "settings";
    MenuItemsIds["ALERTS"] = "alerts";
    MenuItemsIds["FULLSCREEEN"] = "fullscreen";
})(MenuItemsIds || (exports.MenuItemsIds = MenuItemsIds = {}));
